# config/grafana-datasources.yaml
# Auto-provisioned data sources for Grafana

apiVersion: 1

datasources:
  - name: Prometheus-test
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki-test
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          url: "$${__value.raw}"

  - name: Tempo-test
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus